apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespaces are set explicitly on each resource in this directory.

resources:
  - namespace.yaml
  - backend-pvc.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
